language: nix

before-deploy:
  - cp -r ./result/docs ./docs
  - unlink ./result

branches:
  only:
    - master

deploy:
  provider: pages:git
  edge: true
  local_dir: ./docs
  target_branch: gh-pages
  # Set in the settings page of your repository, as a secure variable
  token: $GITHUB_TOKEN  
