#!/usr/bin/env bash

set -e

pubDir=./docs
htmlDir=$(nix-build --no-out-link ./default.nix)

rm -rf $pubDir
cp -rf "$htmlDir" $pubDir
chmod -R u+w $pubDir
git add ./*.md
git add $pubDir
git commit -m "Publishing new content"
